import doctor from './doctor'
import condition from './condition'
import testimonial from './testimonial'
import faqItem from './faqItem'
import trustBadge from './trustBadge'
import navLink from './navLink'
import footer from './footer'
import hospital from './hospital'
import insurance from './insurance'
import aboutDoctor from './aboutDoctor'
import healthVideos from './healthVideos'
import surgicalTeam from './surgicalTeam'
import clinicLocation from './clinicLocation'
import conditionsPage from './conditionsPage'
import masterConditionPage from './masterConditionPage'
import treatmentsPage from './masterTreatmentsPage'
import eachTreatment from './eachTreatment'
import eachCondition from './eachCondition'
import ContactPage from './ContactPage'
import aboutUsPage from './aboutUsPage'
import homePage from './homePage'
import globalCtaForEachCondition from './globalctaforEachConditon'
import blog from './blog'
import insurancePage from './insurancePage'

export const schemaTypes = [doctor, condition, testimonial, faqItem, trustBadge, navLink, footer, hospital, insurance, aboutDoctor, healthVideos, surgicalTeam, clinicLocation, conditionsPage, masterConditionPage, treatmentsPage, eachTreatment, eachCondition, ContactPage, aboutUsPage, homePage, globalCtaForEachCondition, blog, insurancePage]
